services:
  - type: web
    name: equiti-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeployTrigger: commit
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_TTL
        value: 7d
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: sohaib101malik@gmail.com
      - key: ADMIN_USERNAME
        value: sohaib101malik
      - key: ADMIN_PASSWORD
        value: Google1234@
      - key: ADMIN_FULL_NAME
        value: Sohaib Malik
      - key: MONGO_URI
        sync: false
